/**
 * OpenAI-compatible JSON Schema for PropertyAnalysis (strict mode).
 * Keep in sync with src/types.ts PropertyAnalysis.
 */
export const propertyAnalysisJsonSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    title: { type: "string" },
    price: { type: "string" },
    bedrooms: { type: "string" },
    bathrooms: { type: "string" },
    propertyType: { type: "string" },
    location: {
      type: "object",
      additionalProperties: false,
      properties: {
        address: { type: "string" },
        postcode: { type: "string" },
        town: { type: "string" },
      },
      required: ["address", "postcode", "town"],
    },
    summary: { type: "string" },
    specs: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          label: { type: "string" },
          value: { type: "string" },
        },
        required: ["label", "value"],
      },
    },
    scores: {
      type: "object",
      additionalProperties: false,
      properties: {
        overall: { type: "number" },
        valueForMoney: { type: "number" },
        locationRating: { type: "number" },
        conditionRating: { type: "number" },
        investmentScore: { type: "number" },
        marketScore: { type: "number" },
        rentalScore: { type: "number" },
        growthPotential: { type: "string", enum: ["Low", "Medium", "High"] },
        riskLevel: { type: "string", enum: ["Low", "Medium", "High"] },
        confidenceScore: { type: "number" },
      },
      required: [
        "overall",
        "valueForMoney",
        "locationRating",
        "conditionRating",
        "investmentScore",
        "marketScore",
        "rentalScore",
        "growthPotential",
        "riskLevel",
        "confidenceScore",
      ],
    },
    valuation: {
      type: "object",
      additionalProperties: false,
      properties: {
        conservative: { type: "string" },
        fair: { type: "string" },
        optimistic: { type: "string" },
        forecast1y: { type: "string" },
        forecast3y: { type: "string" },
        forecast5y: { type: "string" },
        forecast10y: { type: "string" },
      },
      required: [
        "conservative",
        "fair",
        "optimistic",
        "forecast1y",
        "forecast3y",
        "forecast5y",
        "forecast10y",
      ],
    },
    investmentMetrics: {
      type: "object",
      additionalProperties: false,
      properties: {
        estimatedRent: { type: "string" },
        grossYield: { type: "string" },
        netYield: { type: "string" },
        roi: { type: "string" },
        cashflow: { type: "string" },
        stampDuty: { type: "string" },
        breakEven: { type: "string" },
        irr: { type: "string" },
        growthReasoning: { type: "string" },
      },
      required: [
        "estimatedRent",
        "grossYield",
        "netYield",
        "roi",
        "cashflow",
        "stampDuty",
        "breakEven",
        "irr",
        "growthReasoning",
      ],
    },
    marketAndRental: {
      type: "object",
      additionalProperties: false,
      properties: {
        supplyDemand: { type: "string" },
        timeOnMarket: { type: "string" },
        priceTrend: { type: "string" },
        vacancyRates: { type: "string" },
        tenantProfile: { type: "string" },
        airbnbPotential: { type: "string" },
      },
      required: [
        "supplyDemand",
        "timeOnMarket",
        "priceTrend",
        "vacancyRates",
        "tenantProfile",
        "airbnbPotential",
      ],
    },
    riskAnalysis: {
      type: "object",
      additionalProperties: false,
      properties: {
        floodRisk: { type: "string" },
        subsidence: { type: "string" },
        planningDevelopments: { type: "string" },
        leaseholdIssues: { type: "string" },
        fireSafety: { type: "string" },
        insuranceRisk: { type: "string" },
      },
      required: [
        "floodRisk",
        "subsidence",
        "planningDevelopments",
        "leaseholdIssues",
        "fireSafety",
        "insuranceRisk",
      ],
    },
    riskTones: {
      type: "object",
      additionalProperties: false,
      properties: {
        floodRisk: { type: "string", enum: ["positive", "caution", "negative", "neutral"] },
        subsidence: { type: "string", enum: ["positive", "caution", "negative", "neutral"] },
        planningDevelopments: {
          type: "string",
          enum: ["positive", "caution", "negative", "neutral"],
        },
        leaseholdIssues: { type: "string", enum: ["positive", "caution", "negative", "neutral"] },
        fireSafety: { type: "string", enum: ["positive", "caution", "negative", "neutral"] },
        insuranceRisk: { type: "string", enum: ["positive", "caution", "negative", "neutral"] },
      },
      required: [
        "floodRisk",
        "subsidence",
        "planningDevelopments",
        "leaseholdIssues",
        "fireSafety",
        "insuranceRisk",
      ],
    },
    marketEvidence: {
      type: "object",
      additionalProperties: false,
      properties: {
        askingVsSoldEvidence: { type: "string" },
        competingSupply: { type: "string" },
        pricePerSqmOrSqft: { type: "string" },
        negotiationLevers: { type: "string" },
      },
      required: [
        "askingVsSoldEvidence",
        "competingSupply",
        "pricePerSqmOrSqft",
        "negotiationLevers",
      ],
    },
    locationIntelligence: {
      type: "object",
      additionalProperties: false,
      properties: {
        plannedInfrastructure: { type: "string" },
        populationGrowth: { type: "string" },
        regenerationProjects: { type: "string" },
        walkability: { type: "string" },
      },
      required: [
        "plannedInfrastructure",
        "populationGrowth",
        "regenerationProjects",
        "walkability",
      ],
    },
    advanced: {
      type: "object",
      additionalProperties: false,
      properties: {
        undervaluedExplanation: { type: "string" },
        renovationROI: { type: "string" },
        developmentOpportunity: { type: "string" },
      },
      required: ["undervaluedExplanation", "renovationROI", "developmentOpportunity"],
    },
    propertyWorks: {
      type: "object",
      additionalProperties: false,
      properties: {
        extensionsAndAlterations: { type: "string" },
        planningApplications: { type: "string" },
        valueImpact: { type: "string" },
        certainty: { type: "string" },
      },
      required: [
        "extensionsAndAlterations",
        "planningApplications",
        "valueImpact",
        "certainty",
      ],
    },
    dueDiligence: {
      type: "object",
      additionalProperties: false,
      properties: {
        epcAndEnergy: { type: "string" },
        broadbandAndMobile: { type: "string" },
        tenureAndLegal: { type: "string" },
        councilTaxAndParking: { type: "string" },
        purchaseCosts: { type: "string" },
        environmentalOther: { type: "string" },
        ownershipAndChain: { type: "string" },
        recommendedNextSteps: { type: "array", items: { type: "string" } },
      },
      required: [
        "epcAndEnergy",
        "broadbandAndMobile",
        "tenureAndLegal",
        "councilTaxAndParking",
        "purchaseCosts",
        "environmentalOther",
        "ownershipAndChain",
        "recommendedNextSteps",
      ],
    },
    pros: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          title: { type: "string" },
          desc: { type: "string" },
          category: { type: "string" },
        },
        required: ["title", "desc", "category"],
      },
    },
    cons: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          title: { type: "string" },
          desc: { type: "string" },
          category: { type: "string" },
        },
        required: ["title", "desc", "category"],
      },
    },
    soldHistory: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          year: { type: "string" },
          price: { type: "string" },
          source: { type: "string" },
          description: { type: "string" },
        },
        required: ["year", "price", "source", "description"],
      },
    },
    comparableSales: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          address: { type: "string" },
          price: { type: "string" },
          soldDate: { type: "string" },
          similarity: { type: "string" },
        },
        required: ["address", "price", "soldDate", "similarity"],
      },
    },
    areaAnalysis: {
      type: "object",
      additionalProperties: false,
      properties: {
        schools: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              name: { type: "string" },
              distance: { type: "string" },
              rating: { type: "string" },
            },
            required: ["name", "distance", "rating"],
          },
        },
        transport: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              type: { type: "string" },
              line: { type: "string" },
              time: { type: "string" },
            },
            required: ["type", "line", "time"],
          },
        },
        crimeSafety: {
          type: "object",
          additionalProperties: false,
          properties: {
            rating: { type: "string" },
            description: { type: "string" },
          },
          required: ["rating", "description"],
        },
        demographics: { type: "string" },
        amenities: { type: "array", items: { type: "string" } },
        futureOutlook: { type: "string" },
      },
      required: [
        "schools",
        "transport",
        "crimeSafety",
        "demographics",
        "amenities",
        "futureOutlook",
      ],
    },
    buyingSuitability: { type: "string" },
    viewingChecks: { type: "array", items: { type: "string" } },
    offerStrategy: {
      type: "object",
      additionalProperties: false,
      properties: {
        lowOffer: { type: "string" },
        fairOffer: { type: "string" },
        premiumOffer: { type: "string" },
        negotiationTips: { type: "array", items: { type: "string" } },
      },
      required: ["lowOffer", "fairOffer", "premiumOffer", "negotiationTips"],
    },
    agentQuestions: { type: "array", items: { type: "string" } },
  },
  required: [
    "title",
    "price",
    "bedrooms",
    "bathrooms",
    "propertyType",
    "location",
    "summary",
    "specs",
    "scores",
    "valuation",
    "investmentMetrics",
    "marketAndRental",
    "riskAnalysis",
    "riskTones",
    "locationIntelligence",
    "advanced",
    "propertyWorks",
    "dueDiligence",
    "marketEvidence",
    "pros",
    "cons",
    "soldHistory",
    "comparableSales",
    "areaAnalysis",
    "buyingSuitability",
    "viewingChecks",
    "offerStrategy",
    "agentQuestions",
  ],
} as const;
